apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask-deployment
  labels:
    deployment: myflask
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: myflask
  template:
    metadata:
      labels:
        app: myflask
    spec:
      containers:
        - name: myflask-container
          image: myflask
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            exec: 
              command:
                - cat
                - /tmp/run.txt
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 2
      restartPolicy: Always
